2025-06-12 19:05:17,670 INFO: Restaurant startup [in C:\Users\rob mc neil\Desktop\CAPS-WA-POS\_wapos\wa_pos.py:31]
2025-06-12 19:45:52,870 INFO: Restaurant startup [in c:\Users\rob mc neil\Desktop\CAPS-WA-POS\_wapos\tempCodeRunnerFile.py:33]
2025-06-12 19:45:53,009 INFO: Created admin role [in c:\Users\rob mc neil\Desktop\CAPS-WA-POS\_wapos\tempCodeRunnerFile.py:64]
2025-06-12 19:45:53,187 INFO: Created admin user [in c:\Users\rob mc neil\Desktop\CAPS-WA-POS\_wapos\tempCodeRunnerFile.py:84]
2025-06-12 19:56:53,502 INFO: Restaurant startup [in C:\Users\rob mc neil\Desktop\CAPS-WA-POS\_wapos\wa_pos.py:31]
2025-06-12 19:59:23,250 ERROR: Exception on /login [POST] [in C:\Users\rob mc neil\Desktop\CAPS-WA-POS\environment\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\rob mc neil\Desktop\CAPS-WA-POS\environment\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rob mc neil\Desktop\CAPS-WA-POS\environment\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rob mc neil\Desktop\CAPS-WA-POS\environment\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rob mc neil\Desktop\CAPS-WA-POS\environment\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rob mc neil\Desktop\CAPS-WA-POS\_wapos\routes\auth_routes.py", line 21, in login
    user = LoginService.authenticate_user(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rob mc neil\Desktop\CAPS-WA-POS\_wapos\services\auth\login_services.py", line 28, in authenticate_user
    user = User.query.filter_by(email=email).first()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rob mc neil\Desktop\CAPS-WA-POS\environment\Lib\site-packages\sqlalchemy\orm\query.py", line 2759, in first
    return self.limit(1)._iter().first()  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rob mc neil\Desktop\CAPS-WA-POS\environment\Lib\site-packages\sqlalchemy\orm\query.py", line 2857, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
                                                  ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rob mc neil\Desktop\CAPS-WA-POS\environment\Lib\site-packages\sqlalchemy\orm\session.py", line 2365, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rob mc neil\Desktop\CAPS-WA-POS\environment\Lib\site-packages\sqlalchemy\orm\session.py", line 2239, in _execute_internal
    bind = self.get_bind(**bind_arguments)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rob mc neil\Desktop\CAPS-WA-POS\environment\Lib\site-packages\flask_sqlalchemy\session.py", line 53, in get_bind
    engines = self._db.engines
              ^^^^^^^^^^^^^^^^
  File "C:\Users\rob mc neil\Desktop\CAPS-WA-POS\environment\Lib\site-packages\flask_sqlalchemy\extension.py", line 690, in engines
    raise RuntimeError(
RuntimeError: The current Flask app is not registered with this 'SQLAlchemy' instance. Did you forget to call 'init_app', or did you create multiple 'SQLAlchemy' instances?
2025-06-12 20:05:41,607 ERROR: Exception on /login [POST] [in C:\Users\rob mc neil\Desktop\CAPS-WA-POS\environment\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\rob mc neil\Desktop\CAPS-WA-POS\environment\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rob mc neil\Desktop\CAPS-WA-POS\environment\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rob mc neil\Desktop\CAPS-WA-POS\environment\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rob mc neil\Desktop\CAPS-WA-POS\environment\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rob mc neil\Desktop\CAPS-WA-POS\_wapos\routes\auth_routes.py", line 21, in login
    user = LoginService.authenticate_user(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rob mc neil\Desktop\CAPS-WA-POS\_wapos\services\auth\login_services.py", line 28, in authenticate_user
    user = User.query.filter_by(email=email).first()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rob mc neil\Desktop\CAPS-WA-POS\environment\Lib\site-packages\sqlalchemy\orm\query.py", line 2759, in first
    return self.limit(1)._iter().first()  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rob mc neil\Desktop\CAPS-WA-POS\environment\Lib\site-packages\sqlalchemy\orm\query.py", line 2857, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
                                                  ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rob mc neil\Desktop\CAPS-WA-POS\environment\Lib\site-packages\sqlalchemy\orm\session.py", line 2365, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rob mc neil\Desktop\CAPS-WA-POS\environment\Lib\site-packages\sqlalchemy\orm\session.py", line 2239, in _execute_internal
    bind = self.get_bind(**bind_arguments)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rob mc neil\Desktop\CAPS-WA-POS\environment\Lib\site-packages\flask_sqlalchemy\session.py", line 53, in get_bind
    engines = self._db.engines
              ^^^^^^^^^^^^^^^^
  File "C:\Users\rob mc neil\Desktop\CAPS-WA-POS\environment\Lib\site-packages\flask_sqlalchemy\extension.py", line 690, in engines
    raise RuntimeError(
RuntimeError: The current Flask app is not registered with this 'SQLAlchemy' instance. Did you forget to call 'init_app', or did you create multiple 'SQLAlchemy' instances?
2025-06-12 20:06:55,148 INFO: Restaurant startup [in C:\Users\rob mc neil\Desktop\CAPS-WA-POS\_wapos\wa_pos.py:31]
2025-06-12 20:07:13,783 ERROR: Exception on /login [POST] [in C:\Users\rob mc neil\Desktop\CAPS-WA-POS\environment\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\rob mc neil\Desktop\CAPS-WA-POS\environment\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rob mc neil\Desktop\CAPS-WA-POS\environment\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rob mc neil\Desktop\CAPS-WA-POS\environment\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rob mc neil\Desktop\CAPS-WA-POS\environment\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rob mc neil\Desktop\CAPS-WA-POS\_wapos\routes\auth_routes.py", line 21, in login
    user = LoginService.authenticate_user(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rob mc neil\Desktop\CAPS-WA-POS\_wapos\services\auth\login_services.py", line 28, in authenticate_user
    user = current_app.db.session.query(User).filter_by(email=email).first()
           ^^^^^^^^^^^^^^
AttributeError: 'Flask' object has no attribute 'db'
2025-06-12 20:31:59,531 INFO: Restaurant startup [in C:\Users\rob mc neil\Desktop\CAPS-WA-POS\_wapos\wa_pos.py:32]
2025-06-12 20:32:08,891 ERROR: Exception on /login [POST] [in C:\Users\rob mc neil\Desktop\CAPS-WA-POS\environment\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\rob mc neil\Desktop\CAPS-WA-POS\environment\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rob mc neil\Desktop\CAPS-WA-POS\environment\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rob mc neil\Desktop\CAPS-WA-POS\environment\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\rob mc neil\Desktop\CAPS-WA-POS\environment\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rob mc neil\Desktop\CAPS-WA-POS\environment\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rob mc neil\Desktop\CAPS-WA-POS\_wapos\routes\auth_routes.py", line 21, in login
    user = LoginService.authenticate_user(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rob mc neil\Desktop\CAPS-WA-POS\_wapos\services\auth\login_services.py", line 28, in authenticate_user
    user = current_app.db.session.query(User).filter_by(email=email).first()
           ^^^^^^^^^^^^^^
AttributeError: 'Flask' object has no attribute 'db'
